name: "CI"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      checks: write
    env:
      RAILS_ENV: test
    strategy:
      fail-fast: true
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@d37167af451eb51448db3354e1057b75c4b268f7
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run RSpec Tests
        timeout-minutes: 20
        run: bundle exec rspec -f doc
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@d37167af451eb51448db3354e1057b75c4b268f7
        with:
          bundler-cache: true
          ruby-version: "3.2"
      - name: Bundle Audit Check
        run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - name: Setup Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@5f528da5c95691c4cf42ff76a4d10854b62cbb82
